# .streamlit/secrets.toml の設定例
# このファイルの内容を .streamlit/secrets.toml にコピーして使用してください。
# ※ secrets.toml は絶対にGitHubにコミットしないでください (通常 .gitignore に含まれています)

[passwords]
# generate_password.pyツールなどを使用して生成したSHA256ハッシュ値を指定します
admin = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918" # "admin"のハッシュ
user1 = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92" # "123456"のハッシュ
